#!/bin/bash
set -e

SOLID="transgender-alt money-bill-wave angle-right battery-three-quarters calendar pencil-alt sitemap stopwatch globe-americas bars cogs book hand-middle-finger cloud network-wired signal server envelope book server images skull-crossbones bomb book-dead terminal adjust"
BRANDS="linux youtube ethereum twitter github twitch linkedin discord mastodon"
REGULAR=""

DIR="static/assets/fonts"
URL="https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/svgs/brands/"
echo ""
echo ""
for i in ${BRANDS}; do
  svg="${i}.svg"
  echo ""
  echo "${URL}/${svg}"
  wget -O "${DIR}/${svg}" "${URL}/${svg}"
done

DIR="static/assets/fonts"
URL="https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/svgs/solid/"
echo ""
echo ""
for i in ${SOLID}; do
  svg="${i}.svg"
  echo ""
  echo "${URL}/${svg}"
  wget -O "${DIR}/${svg}" "${URL}/${svg}"
done


DIR="static/assets/fonts"
URL="https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/svgs/regular/"
echo ""
echo ""
for i in ${REGULAR}; do
  svg="${i}.svg"
  echo ""
  echo "${URL}/${svg}"
  wget -O "${DIR}/${svg}" "${URL}/${svg}"
done

